name: equidi1 action
on:
  schedule:
    - cron: "13 */4 * * *"
    
  workflow_dispatch:

jobs:
  update-stream:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v3

      - name: updating equidia
        run: sh ressources/froth/py/equidv1b.sh

      - name: setup git config
        run: |
          git config user.name "equidia bot"
          git config user.email "<>"
      - name: commit
        run: |
          git pull
          git add all.m3u
          git commit -m "equidia updated"
          git push origin master
