name: murlb

on:
  schedule:
    - cron: '03 */23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "murlb bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests module
        run: python3 -m pip install requests

      - name: fetch content murlb
        run: |
          final_url=$(python3 ressources/kuw/murlb.py)
          echo "murstrm=${final_url}" >> $GITHUB_ENV

      - name: Replace Text
        run: |
          murstrm=${murstrm}
          sed -i "/MTV LBN/{n;s|.*|'"$murstrm"'|}" all.m3u
          sed -i "/MTV LBN/{n;s|.*|'"$murstrm"'|}" ressources/allgr.m3u

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git add all.m3u ressources/allgr.m3u
          git commit -m "murlb updated"
          git push
