name: onelb

on:
  schedule:
    - cron: '44 */4 * * *'
  workflow_dipatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "onelb bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests module
        run: python3 -m pip install requests

      - name: fetch content onelb
        run: |
          final_url=$(python3 ressources/kuw/onelb.py)
          echo "onestrm=${final_url}" >> $GITHUB_ENV

      - name: Replace Text
        run: |
          onestrm=${onestrm}
          sed -i "/ONE TV LBN/{n;s|.*|"$onestrm"|}" all.m3u
          sed -i "/ONE TV LBN/{n;s|.*|"$onestrm"|}" ressources/allgr.m3u

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git add all.m3u ressources/allgr.m3u
          git commit -m "onelb updated"
          git push
